import { css } from "css-native";

export const rounded = (value: TemplateStringsArray) => css`
  border-radius: ${value[0]};
`;
export const rounded_xs = rounded`var(--radius-xs)`;
export const rounded_sm = rounded`var(--radius-sm)`;
export const rounded_md = rounded`var(--radius-md)`;
export const rounded_lg = rounded`var(--radius-lg)`;
export const rounded_xl = rounded`var(--radius-xl)`;
export const rounded_2xl = rounded`var(--radius-2xl)`;
export const rounded_3xl = rounded`var(--radius-3xl)`;
export const rounded_4xl = rounded`var(--radius-4xl)`;
export const rounded_none = rounded`0`;
export const rounded_full = rounded`999999px`;
export const rounded_s = (value: TemplateStringsArray) => css`
  border-start-start-radius: ${value[0]};
  border-end-start-radius: ${value[0]};
`;
export const rounded_s_xs = rounded_s`var(--radius-xs)`;
export const rounded_s_sm = rounded_s`var(--radius-sm)`;
export const rounded_s_md = rounded_s`var(--radius-md)`;
export const rounded_s_lg = rounded_s`var(--radius-lg)`;
export const rounded_s_xl = rounded_s`var(--radius-xl)`;
export const rounded_s_2xl = rounded_s`var(--radius-2xl)`;
export const rounded_s_3xl = rounded_s`var(--radius-3xl)`;
export const rounded_s_4xl = rounded_s`var(--radius-4xl)`;
export const rounded_s_none = rounded_s`0`;
export const rounded_s_full = rounded_s`999999px`;
export const rounded_e = (value: TemplateStringsArray) => css`
  border-start-end-radius: ${value[0]};
  border-end-end-radius: ${value[0]};
`;
export const rounded_e_xs = rounded_e`var(--radius-xs)`;
export const rounded_e_sm = rounded_e`var(--radius-sm)`;
export const rounded_e_md = rounded_e`var(--radius-md)`;
export const rounded_e_lg = rounded_e`var(--radius-lg)`;
export const rounded_e_xl = rounded_e`var(--radius-xl)`;
export const rounded_e_2xl = rounded_e`var(--radius-2xl)`;
export const rounded_e_3xl = rounded_e`var(--radius-3xl)`;
export const rounded_e_4xl = rounded_e`var(--radius-4xl)`;
export const rounded_e_none = rounded_e`0`;
export const rounded_e_full = rounded_e`999999px`;
export const rounded_t = (value: TemplateStringsArray) => css`
  border-top-left-radius: ${value[0]};
  border-top-right-radius: ${value[0]};
`;
export const rounded_t_xs = rounded_t`var(--radius-xs)`;
export const rounded_t_sm = rounded_t`var(--radius-sm)`;
export const rounded_t_md = rounded_t`var(--radius-md)`;
export const rounded_t_lg = rounded_t`var(--radius-lg)`;
export const rounded_t_xl = rounded_t`var(--radius-xl)`;
export const rounded_t_2xl = rounded_t`var(--radius-2xl)`;
export const rounded_t_3xl = rounded_t`var(--radius-3xl)`;
export const rounded_t_4xl = rounded_t`var(--radius-4xl)`;
export const rounded_t_none = rounded_t`0`;
export const rounded_t_full = rounded_t`999999px`;
export const rounded_r = (value: TemplateStringsArray) => css`
  border-top-right-radius: ${value[0]};
  border-bottom-right-radius: ${value[0]};
`;
export const rounded_r_xs = rounded_r`var(--radius-xs)`;
export const rounded_r_sm = rounded_r`var(--radius-sm)`;
export const rounded_r_md = rounded_r`var(--radius-md)`;
export const rounded_r_lg = rounded_r`var(--radius-lg)`;
export const rounded_r_xl = rounded_r`var(--radius-xl)`;
export const rounded_r_2xl = rounded_r`var(--radius-2xl)`;
export const rounded_r_3xl = rounded_r`var(--radius-3xl)`;
export const rounded_r_4xl = rounded_r`var(--radius-4xl)`;
export const rounded_r_none = rounded_r`0`;
export const rounded_r_full = rounded_r`999999px`;
export const rounded_b = (value: TemplateStringsArray) => css`
  border-bottom-left-radius: ${value[0]};
  border-bottom-right-radius: ${value[0]};
`;
export const rounded_b_xs = rounded_b`var(--radius-xs)`;
export const rounded_b_sm = rounded_b`var(--radius-sm)`;
export const rounded_b_md = rounded_b`var(--radius-md)`;
export const rounded_b_lg = rounded_b`var(--radius-lg)`;
export const rounded_b_xl = rounded_b`var(--radius-xl)`;
export const rounded_b_2xl = rounded_b`var(--radius-2xl)`;
export const rounded_b_3xl = rounded_b`var(--radius-3xl)`;
export const rounded_b_4xl = rounded_b`var(--radius-4xl)`;
export const rounded_b_none = rounded_b`0`;
export const rounded_b_full = rounded_b`999999px`;
export const rounded_l = (value: TemplateStringsArray) => css`
  border-top-left-radius: ${value[0]};
  border-bottom-left-radius: ${value[0]};
`;
export const rounded_l_xs = rounded_l`var(--radius-xs)`;
export const rounded_l_sm = rounded_l`var(--radius-sm)`;
export const rounded_l_md = rounded_l`var(--radius-md)`;
export const rounded_l_lg = rounded_l`var(--radius-lg)`;
export const rounded_l_xl = rounded_l`var(--radius-xl)`;
export const rounded_l_2xl = rounded_l`var(--radius-2xl)`;
export const rounded_l_3xl = rounded_l`var(--radius-3xl)`;
export const rounded_l_4xl = rounded_l`var(--radius-4xl)`;
export const rounded_l_none = rounded_l`0`;
export const rounded_l_full = rounded_l`999999px`;
export const rounded_ss = (value: TemplateStringsArray) => css`
  border-start-start-radius: ${value[0]};
`;
export const rounded_ss_xs = rounded_ss`var(--radius-xs)`;
export const rounded_ss_sm = rounded_ss`var(--radius-sm)`;
export const rounded_ss_md = rounded_ss`var(--radius-md)`;
export const rounded_ss_lg = rounded_ss`var(--radius-lg)`;
export const rounded_ss_xl = rounded_ss`var(--radius-xl)`;
export const rounded_ss_2xl = rounded_ss`var(--radius-2xl)`;
export const rounded_ss_3xl = rounded_ss`var(--radius-3xl)`;
export const rounded_ss_4xl = rounded_ss`var(--radius-4xl)`;
export const rounded_ss_none = rounded_ss`0`;
export const rounded_ss_full = rounded_ss`999999px`;
export const rounded_se = (value: TemplateStringsArray) => css`
  border-start-end-radius: ${value[0]};
`;
export const rounded_se_xs = rounded_se`var(--radius-xs)`;
export const rounded_se_sm = rounded_se`var(--radius-sm)`;
export const rounded_se_md = rounded_se`var(--radius-md)`;
export const rounded_se_lg = rounded_se`var(--radius-lg)`;
export const rounded_se_xl = rounded_se`var(--radius-xl)`;
export const rounded_se_2xl = rounded_se`var(--radius-2xl)`;
export const rounded_se_3xl = rounded_se`var(--radius-3xl)`;
export const rounded_se_4xl = rounded_se`var(--radius-4xl)`;
export const rounded_se_none = rounded_se`0`;
export const rounded_se_full = rounded_se`999999px`;
export const rounded_ee = (value: TemplateStringsArray) => css`
  border-end-end-radius: ${value[0]};
`;
export const rounded_ee_xs = rounded_ee`var(--radius-xs)`;
export const rounded_ee_sm = rounded_ee`var(--radius-sm)`;
export const rounded_ee_md = rounded_ee`var(--radius-md)`;
export const rounded_ee_lg = rounded_ee`var(--radius-lg)`;
export const rounded_ee_xl = rounded_ee`var(--radius-xl)`;
export const rounded_ee_2xl = rounded_ee`var(--radius-2xl)`;
export const rounded_ee_3xl = rounded_ee`var(--radius-3xl)`;
export const rounded_ee_4xl = rounded_ee`var(--radius-4xl)`;
export const rounded_ee_none = rounded_ee`0`;
export const rounded_ee_full = rounded_ee`999999px`;
export const rounded_es = (value: TemplateStringsArray) => css`
  border-end-start-radius: ${value[0]};
`;
export const rounded_es_xs = rounded_es`var(--radius-xs)`;
export const rounded_es_sm = rounded_es`var(--radius-sm)`;
export const rounded_es_md = rounded_es`var(--radius-md)`;
export const rounded_es_lg = rounded_es`var(--radius-lg)`;
export const rounded_es_xl = rounded_es`var(--radius-xl)`;
export const rounded_es_2xl = rounded_es`var(--radius-2xl)`;
export const rounded_es_3xl = rounded_es`var(--radius-3xl)`;
export const rounded_es_4xl = rounded_es`var(--radius-4xl)`;
export const rounded_es_none = rounded_es`0`;
export const rounded_es_full = rounded_es`999999px`;
export const rounded_tl = (value: TemplateStringsArray) => css`
  border-top-left-radius: ${value[0]};
`;
export const rounded_tl_xs = rounded_tl`var(--radius-xs)`;
export const rounded_tl_sm = rounded_tl`var(--radius-sm)`;
export const rounded_tl_md = rounded_tl`var(--radius-md)`;
export const rounded_tl_lg = rounded_tl`var(--radius-lg)`;
export const rounded_tl_xl = rounded_tl`var(--radius-xl)`;
export const rounded_tl_2xl = rounded_tl`var(--radius-2xl)`;
export const rounded_tl_3xl = rounded_tl`var(--radius-3xl)`;
export const rounded_tl_4xl = rounded_tl`var(--radius-4xl)`;
export const rounded_tl_none = rounded_tl`0`;
export const rounded_tl_full = rounded_tl`999999px`;
export const rounded_tr = (value: TemplateStringsArray) => css`
  border-top-right-radius: ${value[0]};
`;
export const rounded_tr_xs = rounded_tr`var(--radius-xs)`;
export const rounded_tr_sm = rounded_tr`var(--radius-sm)`;
export const rounded_tr_md = rounded_tr`var(--radius-md)`;
export const rounded_tr_lg = rounded_tr`var(--radius-lg)`;
export const rounded_tr_xl = rounded_tr`var(--radius-xl)`;
export const rounded_tr_2xl = rounded_tr`var(--radius-2xl)`;
export const rounded_tr_3xl = rounded_tr`var(--radius-3xl)`;
export const rounded_tr_4xl = rounded_tr`var(--radius-4xl)`;
export const rounded_tr_none = rounded_tr`0`;
export const rounded_tr_full = rounded_tr`999999px`;
export const rounded_br = (value: TemplateStringsArray) => css`
  border-bottom-right-radius: ${value[0]};
`;
export const rounded_br_xs = rounded_br`var(--radius-xs)`;
export const rounded_br_sm = rounded_br`var(--radius-sm)`;
export const rounded_br_md = rounded_br`var(--radius-md)`;
export const rounded_br_lg = rounded_br`var(--radius-lg)`;
export const rounded_br_xl = rounded_br`var(--radius-xl)`;
export const rounded_br_2xl = rounded_br`var(--radius-2xl)`;
export const rounded_br_3xl = rounded_br`var(--radius-3xl)`;
export const rounded_br_4xl = rounded_br`var(--radius-4xl)`;
export const rounded_br_none = rounded_br`0`;
export const rounded_br_full = rounded_br`999999px`;
export const rounded_bl = (value: TemplateStringsArray) => css`
  border-bottom-left-radius: ${value[0]};
`;
export const rounded_bl_xs = rounded_bl`var(--radius-xs)`;
export const rounded_bl_sm = rounded_bl`var(--radius-sm)`;
export const rounded_bl_md = rounded_bl`var(--radius-md)`;
export const rounded_bl_lg = rounded_bl`var(--radius-lg)`;
export const rounded_bl_xl = rounded_bl`var(--radius-xl)`;
export const rounded_bl_2xl = rounded_bl`var(--radius-2xl)`;
export const rounded_bl_3xl = rounded_bl`var(--radius-3xl)`;
export const rounded_bl_4xl = rounded_bl`var(--radius-4xl)`;
export const rounded_bl_none = rounded_bl`0`;
export const rounded_bl_full = rounded_bl`999999px`;
