import { css } from "css-native";

export const rounded = (value: string) => css`
  border-radius: ${value};
`;
export const rounded_xs = rounded("var(--rounded-xs)");
export const rounded_sm = rounded("var(--rounded-sm)");
export const rounded_md = rounded("var(--rounded-md)");
export const rounded_lg = rounded("var(--rounded-lg)");
export const rounded_xl = rounded("var(--rounded-xl)");
export const rounded_2xl = rounded("var(--rounded-2xl)");
export const rounded_3xl = rounded("var(--rounded-3xl)");
export const rounded_4xl = rounded("var(--rounded-4xl)");
export const rounded_none = rounded("0");
export const rounded_full = rounded("999999px");
export const rounded_s = (value: string) => css`
  border-start-start-radius: ${value};
  border-end-start-radius: ${value};
`;
export const rounded_s_xs = rounded_s("var(--rounded-xs)");
export const rounded_s_sm = rounded_s("var(--rounded-sm)");
export const rounded_s_md = rounded_s("var(--rounded-md)");
export const rounded_s_lg = rounded_s("var(--rounded-lg)");
export const rounded_s_xl = rounded_s("var(--rounded-xl)");
export const rounded_s_2xl = rounded_s("var(--rounded-2xl)");
export const rounded_s_3xl = rounded_s("var(--rounded-3xl)");
export const rounded_s_4xl = rounded_s("var(--rounded-4xl)");
export const rounded_s_none = rounded_s("0");
export const rounded_s_full = rounded_s("999999px");
export const rounded_e = (value: string) => css`
  border-start-end-radius: ${value};
  border-end-end-radius: ${value};
`;
export const rounded_e_xs = rounded_e("var(--rounded-xs)");
export const rounded_e_sm = rounded_e("var(--rounded-sm)");
export const rounded_e_md = rounded_e("var(--rounded-md)");
export const rounded_e_lg = rounded_e("var(--rounded-lg)");
export const rounded_e_xl = rounded_e("var(--rounded-xl)");
export const rounded_e_2xl = rounded_e("var(--rounded-2xl)");
export const rounded_e_3xl = rounded_e("var(--rounded-3xl)");
export const rounded_e_4xl = rounded_e("var(--rounded-4xl)");
export const rounded_e_none = rounded_e("0");
export const rounded_e_full = rounded_e("999999px");
export const rounded_t = (value: string) => css`
  border-top-left-radius: ${value};
  border-top-right-radius: ${value};
`;
export const rounded_t_xs = rounded_t("var(--rounded-xs)");
export const rounded_t_sm = rounded_t("var(--rounded-sm)");
export const rounded_t_md = rounded_t("var(--rounded-md)");
export const rounded_t_lg = rounded_t("var(--rounded-lg)");
export const rounded_t_xl = rounded_t("var(--rounded-xl)");
export const rounded_t_2xl = rounded_t("var(--rounded-2xl)");
export const rounded_t_3xl = rounded_t("var(--rounded-3xl)");
export const rounded_t_4xl = rounded_t("var(--rounded-4xl)");
export const rounded_t_none = rounded_t("0");
export const rounded_t_full = rounded_t("999999px");
export const rounded_r = (value: string) => css`
  border-top-right-radius: ${value};
  border-bottom-right-radius: ${value};
`;
export const rounded_r_xs = rounded_r("var(--rounded-xs)");
export const rounded_r_sm = rounded_r("var(--rounded-sm)");
export const rounded_r_md = rounded_r("var(--rounded-md)");
export const rounded_r_lg = rounded_r("var(--rounded-lg)");
export const rounded_r_xl = rounded_r("var(--rounded-xl)");
export const rounded_r_2xl = rounded_r("var(--rounded-2xl)");
export const rounded_r_3xl = rounded_r("var(--rounded-3xl)");
export const rounded_r_4xl = rounded_r("var(--rounded-4xl)");
export const rounded_r_none = rounded_r("0");
export const rounded_r_full = rounded_r("999999px");
export const rounded_b = (value: string) => css`
  border-bottom-left-radius: ${value};
  border-bottom-right-radius: ${value};
`;
export const rounded_b_xs = rounded_b("var(--rounded-xs)");
export const rounded_b_sm = rounded_b("var(--rounded-sm)");
export const rounded_b_md = rounded_b("var(--rounded-md)");
export const rounded_b_lg = rounded_b("var(--rounded-lg)");
export const rounded_b_xl = rounded_b("var(--rounded-xl)");
export const rounded_b_2xl = rounded_b("var(--rounded-2xl)");
export const rounded_b_3xl = rounded_b("var(--rounded-3xl)");
export const rounded_b_4xl = rounded_b("var(--rounded-4xl)");
export const rounded_b_none = rounded_b("0");
export const rounded_b_full = rounded_b("999999px");
export const rounded_l = (value: string) => css`
  border-top-left-radius: ${value};
  border-bottom-left-radius: ${value};
`;
export const rounded_l_xs = rounded_l("var(--rounded-xs)");
export const rounded_l_sm = rounded_l("var(--rounded-sm)");
export const rounded_l_md = rounded_l("var(--rounded-md)");
export const rounded_l_lg = rounded_l("var(--rounded-lg)");
export const rounded_l_xl = rounded_l("var(--rounded-xl)");
export const rounded_l_2xl = rounded_l("var(--rounded-2xl)");
export const rounded_l_3xl = rounded_l("var(--rounded-3xl)");
export const rounded_l_4xl = rounded_l("var(--rounded-4xl)");
export const rounded_l_none = rounded_l("0");
export const rounded_l_full = rounded_l("999999px");
export const rounded_ss = (value: string) => css`
  border-start-start-radius: ${value};
`;
export const rounded_ss_xs = rounded_ss("var(--rounded-xs)");
export const rounded_ss_sm = rounded_ss("var(--rounded-sm)");
export const rounded_ss_md = rounded_ss("var(--rounded-md)");
export const rounded_ss_lg = rounded_ss("var(--rounded-lg)");
export const rounded_ss_xl = rounded_ss("var(--rounded-xl)");
export const rounded_ss_2xl = rounded_ss("var(--rounded-2xl)");
export const rounded_ss_3xl = rounded_ss("var(--rounded-3xl)");
export const rounded_ss_4xl = rounded_ss("var(--rounded-4xl)");
export const rounded_ss_none = rounded_ss("0");
export const rounded_ss_full = rounded_ss("999999px");
export const rounded_se = (value: string) => css`
  border-start-end-radius: ${value};
`;
export const rounded_se_xs = rounded_se("var(--rounded-xs)");
export const rounded_se_sm = rounded_se("var(--rounded-sm)");
export const rounded_se_md = rounded_se("var(--rounded-md)");
export const rounded_se_lg = rounded_se("var(--rounded-lg)");
export const rounded_se_xl = rounded_se("var(--rounded-xl)");
export const rounded_se_2xl = rounded_se("var(--rounded-2xl)");
export const rounded_se_3xl = rounded_se("var(--rounded-3xl)");
export const rounded_se_4xl = rounded_se("var(--rounded-4xl)");
export const rounded_se_none = rounded_se("0");
export const rounded_se_full = rounded_se("999999px");
export const rounded_ee = (value: string) => css`
  border-end-end-radius: ${value};
`;
export const rounded_ee_xs = rounded_ee("var(--rounded-xs)");
export const rounded_ee_sm = rounded_ee("var(--rounded-sm)");
export const rounded_ee_md = rounded_ee("var(--rounded-md)");
export const rounded_ee_lg = rounded_ee("var(--rounded-lg)");
export const rounded_ee_xl = rounded_ee("var(--rounded-xl)");
export const rounded_ee_2xl = rounded_ee("var(--rounded-2xl)");
export const rounded_ee_3xl = rounded_ee("var(--rounded-3xl)");
export const rounded_ee_4xl = rounded_ee("var(--rounded-4xl)");
export const rounded_ee_none = rounded_ee("0");
export const rounded_ee_full = rounded_ee("999999px");
export const rounded_es = (value: string) => css`
  border-end-start-radius: ${value};
`;
export const rounded_es_xs = rounded_es("var(--rounded-xs)");
export const rounded_es_sm = rounded_es("var(--rounded-sm)");
export const rounded_es_md = rounded_es("var(--rounded-md)");
export const rounded_es_lg = rounded_es("var(--rounded-lg)");
export const rounded_es_xl = rounded_es("var(--rounded-xl)");
export const rounded_es_2xl = rounded_es("var(--rounded-2xl)");
export const rounded_es_3xl = rounded_es("var(--rounded-3xl)");
export const rounded_es_4xl = rounded_es("var(--rounded-4xl)");
export const rounded_es_none = rounded_es("0");
export const rounded_es_full = rounded_es("999999px");
export const rounded_tl = (value: string) => css`
  border-top-left-radius: ${value};
`;
export const rounded_tl_xs = rounded_tl("var(--rounded-xs)");
export const rounded_tl_sm = rounded_tl("var(--rounded-sm)");
export const rounded_tl_md = rounded_tl("var(--rounded-md)");
export const rounded_tl_lg = rounded_tl("var(--rounded-lg)");
export const rounded_tl_xl = rounded_tl("var(--rounded-xl)");
export const rounded_tl_2xl = rounded_tl("var(--rounded-2xl)");
export const rounded_tl_3xl = rounded_tl("var(--rounded-3xl)");
export const rounded_tl_4xl = rounded_tl("var(--rounded-4xl)");
export const rounded_tl_none = rounded_tl("0");
export const rounded_tl_full = rounded_tl("999999px");
export const rounded_tr = (value: string) => css`
  border-top-right-radius: ${value};
`;
export const rounded_tr_xs = rounded_tr("var(--rounded-xs)");
export const rounded_tr_sm = rounded_tr("var(--rounded-sm)");
export const rounded_tr_md = rounded_tr("var(--rounded-md)");
export const rounded_tr_lg = rounded_tr("var(--rounded-lg)");
export const rounded_tr_xl = rounded_tr("var(--rounded-xl)");
export const rounded_tr_2xl = rounded_tr("var(--rounded-2xl)");
export const rounded_tr_3xl = rounded_tr("var(--rounded-3xl)");
export const rounded_tr_4xl = rounded_tr("var(--rounded-4xl)");
export const rounded_tr_none = rounded_tr("0");
export const rounded_tr_full = rounded_tr("999999px");
export const rounded_br = (value: string) => css`
  border-bottom-right-radius: ${value};
`;
export const rounded_br_xs = rounded_br("var(--rounded-xs)");
export const rounded_br_sm = rounded_br("var(--rounded-sm)");
export const rounded_br_md = rounded_br("var(--rounded-md)");
export const rounded_br_lg = rounded_br("var(--rounded-lg)");
export const rounded_br_xl = rounded_br("var(--rounded-xl)");
export const rounded_br_2xl = rounded_br("var(--rounded-2xl)");
export const rounded_br_3xl = rounded_br("var(--rounded-3xl)");
export const rounded_br_4xl = rounded_br("var(--rounded-4xl)");
export const rounded_br_none = rounded_br("0");
export const rounded_br_full = rounded_br("999999px");
export const rounded_bl = (value: string) => css`
  border-bottom-left-radius: ${value};
`;
export const rounded_bl_xs = rounded_bl("var(--rounded-xs)");
export const rounded_bl_sm = rounded_bl("var(--rounded-sm)");
export const rounded_bl_md = rounded_bl("var(--rounded-md)");
export const rounded_bl_lg = rounded_bl("var(--rounded-lg)");
export const rounded_bl_xl = rounded_bl("var(--rounded-xl)");
export const rounded_bl_2xl = rounded_bl("var(--rounded-2xl)");
export const rounded_bl_3xl = rounded_bl("var(--rounded-3xl)");
export const rounded_bl_4xl = rounded_bl("var(--rounded-4xl)");
export const rounded_bl_none = rounded_bl("0");
export const rounded_bl_full = rounded_bl("999999px");
